import os
import json
from openai import OpenAI
from src.llm.schema import EnrichRequest, EnrichResponse, CategoryEnum

SYSTEM_PROMPT = """You are an expert scraped content enrichment engine.
Your task is to analyze the provided text content and output STRICT, valid JSON according to this exact specification:

1. "category": Must be strictly one of: ["tech", "finance", "news", "education", "other"].
2. "summary": One concise sentence summarizing the main point.
3. "quality_flags": List of string flags identifying issues (e.g., "missing_author", "short_content", "poor_grammar"). Return empty list [] if clean.
4. "confidence": A float value between 0.0 and 1.0 indicating your confidence in the classification.

RULES:
- Return ONLY valid JSON with no markdown backticks, explanations, or leading/trailing text.
- Never invent a category outside the allowed list.
- If unsure, use category "other" and set confidence below 0.5.
"""

def enrich_content_with_llm(request: EnrichRequest) -> EnrichResponse:
    base_url = os.getenv("LLM_BASE_URL", "http://localhost:11434/v1/")
    api_key = os.getenv("LLM_API_KEY", "ollama")
    model = os.getenv("LLM_MODEL", "gemma3:1b")

    client = OpenAI(base_url=base_url, api_key=api_key)

    response = client.chat.completions.create(
        model=model,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": f"Content to enrich:\n\n{request.content}"}
        ],
        temperature=0.1
    )

    raw_text = response.choices[0].message.content.strip()

    # Clean markdown code blocks if the model accidentally includes them
    if raw_text.startswith("```"):
        lines = raw_text.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        raw_text = "\n".join(lines).strip()

    # Parse and validate with Pydantic schema
    try:
        data = json.loads(raw_text)
        return EnrichResponse(**data)
    except (json.JSONDecodeError, Exception):
        # Fallback handling required by Job Card when output is uncertain/unparseable
        return EnrichResponse(
            category=CategoryEnum.OTHER,
            summary="Unstructured or unparseable response generated by model.",
            quality_flags=["parsing_fallback"],
            confidence=0.3
        )